name: examples

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - run: rustup update stable
      - run: rustup default stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'examples'

      - uses: FedericoCarboni/setup-ffmpeg@v3

      - uses: taiki-e/install-action@v2
        with:
          tool: typst-cli

      - run: cargo install --path .

      - run: |
          echo "DEEPINFRA_KEY=${{ secrets.DEEPINFRA_KEY }}" > keys.env
          echo "GOOGLE_KEY=${{ secrets.GOOGLE_KEY }}" >> keys.env

      - run: |
          mkdir _public
          echo "<html><body><h1>Home page for the examples</h1></body></html>" > _public/index.html

      - name: Run Google example
        run: |
            ./examples/google.sh
            mv _out/release.mp4 _public/google.mp4

      - name: Cleanup
        run: rm keys.env

      - name: Upload static files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
            path: _public/

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment